repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
  # Python
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - '--profile'
          - black
  - repo: 'https://github.com/psf/black-pre-commit-mirror'
    rev: 23.11.0
    hooks:
      - id: black
        args:
          - '--line-length'
          - '100'
        language_version: python3.11
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-comprehensions
          - flake8-functions-names
          - flake8-simplify
  # R (https://github.com/r-lib/styler/)
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9019
    hooks:
      - id: style-files
        args:
          ['--ignore-start="^# styler: off$"', '--ignore-stop="^# styler: on$"']
        exclude: >
          (?x)^(
          tests/testthat/.*/.*\.R(md|nw)?|
          vignettes/customizing_styler\.Rmd|
          tests/testthat/public-api/xyzfile-rnw/random4\.Rnw|
          vignettes/detect-alignment\.Rmd|
          tests/testmanual/addins/.*invalid.*|
          tests/testmanual/addins/r-valid\.R|
          )$
      - id: lintr
        additional_dependencies:
          - r-lib/lintr
        exclude: >
          (?x)^(
          inst/.*|
          man/.*|
          tests/.*|
          touchstone/.*|
          vignettes/.*|
          )$
      - id: roxygenize
        additional_dependencies:
          - r-lib/pkgapi
          - dplyr
          - roxygen2
          - rlang
      - id: use-tidy-description
      - id: spell-check
        exclude: >
          (?x)^(
          \.github/.*\.yaml|
          data/.*|
          tests/testthat/.*|
          touchstone/config\.json|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*-in_tree
          )$
      - id: readme-rmd-rendered
      - id: parsable-R
        exclude: >
          (?x)^(
          tests/testthat/public-api/xyzaddin/addin_region-.*|
          tests/.*invalid.*|
          tests/testthat/rmd/no-tidy-out\.Rmd|
          tests/testthat/escaping/basic-escape-out\.R|
          tests/testthat/indention_operators/.*pipe.*|
          tests/testthat/line_breaks_and_other/.*pipe.*|
          tests/testthat/exception_handling/parser-error\.R|
          tests/testthat/public-api/xyzfile_rmd/random4\.Rmd|
          tests/testthat/rmd/no-tidy-(in|out)\.Rmd|
          )$
      - id: no-browser-statement
        exclude: >
          (?x)^(
          tests/testthat/public-api/xyzaddin/addin_region-.*|
          tests/testmanual/addins/r-invalid\.R|
          tests/testthat/escaping/basic-escape-out\.R|
          tests/testthat/indention_operators/.*pipe.*|
          tests/testthat/line_breaks_and_other/.*pipe.*|
          tests/testthat/exception_handling/parser-error.R|
          tests/testmanual/|
          )$
      - id: deps-in-desc
        exclude: >
          (?x)^(
          touchstone/.*|
          tests/testmanual/addins/.*invalid.*|
          tests/testthat/escaping/basic-escape-out\.R|
          tests/testthat/rnw/011-conditional-eval-out\.Rnw|
          tests/testthat/.*\.R(md)?
          )$
      - id: pkgdown
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: check-yaml
      - id: mixed-line-ending
      - id: file-contents-sorter
        files: "\\.Rbuildignore$"
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
          \.Rd|
          tests/testthat/exception_handling/empty_file\.R|
          tests/testthat/parse_comments/eol_eof_spaces-.*|
          tests/testthat/reference-objects/.*|
          tests/testthat/_snaps/.*|
          )$
  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: 475bf5d96927a1887ce2863ff3075b1d7240bc51
    hooks:
      - id: tidy-gitignore
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
  # Prettier
  - repo: 'https://github.com/pre-commit/mirrors-prettier'
    rev: v3.0.3
    hooks:
      - id: prettier
        types:
          - markdown
          - yaml